language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
install:
  - yarn
script:
  - ./cc-test-reporter before-build npm test -- -u --coverage ./cc-test-reporter after-build --exit-code $?
